### ISSUE TITLE
Use common names in list of countries

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/live-installer#116]
We don't do politics. 

When available use common names for countries.
Never name countries "countries" but "locations". 

Here's an example:

- common_name: `Taiwan`
- official_name: `Taiwan, Province of China`

The official name (as provided by Debian's iso-codes package) is a political statement. It suggests Taiwan is part of China, so that's not good. The common name is neutral, which is good, but if we put it in a table column which header says "country" we make a political statement and suggest that Taiwan is not part of China, so that's not good either.

We need to show Taiwan and not make any political statements.

Whether it actually is part of China or not is neither true of false, it's both true and false depending on who you ask. If you ask us though, our answer should be simple, politics have nothing to do with us. We can and we should just refer to Taiwan as Taiwan, and make sure we don't make bold claims about topics that don't relate to us.

In LMDE 4 Taiwan shows as "Taiwan, Province of China", this needs to be fixed.

**Comment by JulianGro** [comment]
Just for reference: They are not accepting a fix for the issue https://salsa.debian.org/iso-codes-team/iso-codes/-/merge_requests/24

**Comment by JulianGro** [comment]
I just saw Fedoras locale list and thought I should leave a screenshot here as reference:
![VirtualBox_Fedora_15_09_2021_03_51_24](https://user-images.githubusercontent.com/11144627/133357748-5b7d9fd9-21fc-4cf5-bb78-46e668579090.png)
Obviously the "Mandarin Chinese" is weird as that is a spoken language and not a written language. It also excludes Hong Kong which uses Cantonese.
The idea is pretty cool though and makes the list very short. Rather than listing by locale or country, they list by script first and then allow you to select between the locales for that script.

**Comment by clefebvre** [comment]
This is fixed for LMDE 5, we just list locations and trim name details:

![image](https://user-images.githubusercontent.com/1138515/152323173-2259b6a4-1d40-45ef-ad73-3cc0b8aac206.png)

No countries, no politics.

**Comment by JulianGro** [comment]
Well we kind of got the country politics with that still. It says "Chinese" as the language. There is multiple spoken languages that one might call Chinese and there is two scripts.
For example in Hong Kong they speak Cantonese and write traditional Chinese, while in mainland China the official language is mandarin and simplified Chinese. The OS probably doesn't need to know the spoken language, but it definitely should not bunch two different scripts together.
