### ISSUE TITLE
LMDE6 live-installer fails: [Errno 20] Not a directory: '/run/live/medium/live/filesystem.packages-remove'

### ISSUE THREAD

**Issue by ma-bo** [linuxmint/live-installer#152]
stdout/stderr from running /bin/live-installer in a terminal:

************************************
 --> Creating partitions on /dev/sda
mkpart primary 2MB 3202MB
mkswap /dev/sda1
mkswap: /dev/sda1: warning: wiping old swap signature.
Setting up swapspace version 1, size = 3 GiB (3200249856 bytes)
no label, UUID=89dbf57f-0917-41f6-a843-6a067aa82855
mkpart primary 3203MB 100%
mkfs.ext4 -F /dev/sda2
mke2fs 1.47.0 (5-Feb-2023)
/dev/sda2 contains a ext4 file system
	last mounted on /target on Wed Sep 27 18:50:45 2023
Discarding device blocks: done                            
Creating filesystem with 61732608 4k blocks and 15433728 inodes
Filesystem UUID: 374f8d4b-d5dc-4449-9e94-49abf1e19d6c
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000, 7962624, 11239424, 20480000, 23887872

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done     

EXECUTING: 'mount -t ext4 /dev/sda2 /target'
 --> Copying 496410 files
rsync exited with returncode: 0
 --> Chrooting
cp: cannot stat '/run/live/medium/live/vmlinuz': Not a directory
WARNING: No initrd found!!
 --> Removing live packages
[Errno 20] Not a directory: '/run/live/medium/live/filesystem.packages-remove'

**Comment by ma-bo** [comment]
I fixed this issue by:

1) remounting /run/live/medium/ (USB image on /dev/sdb1) as read-write.
2) I removed /run/live/medium/live (0 byte file)
3) mkdir live
4) copied all files from /run/live/medium/casper to /run/live/medium/live
-- except for filesystem.squashfs because it was huge and I didn't think it would be needed to finish the install

**Comment by ma-bo** [comment]
This install was performed using the LMDE6 released 27 Sept 2023, flashing to a thumb drive with rufus-4.2p.exe on Win10 x64.

$ md5sum lmde-6-cinnamon-64bit.iso
34c4a18045220b0de26edb0d8e4d67ef  lmde-6-cinnamon-64bit.iso
$ sha256sum lmde-6-cinnamon-64bit.iso
96963cac1ac2ad4ba38414e618adbcdf64a6faadc33ddf53889fa3dc74d59df4  lmde-6-cinnamon-64bit.iso

**Comment by sblmbb** [comment]
How did you remount it as rw. Can you give step by step process. Im not really ok with linux, but trying to learn

**Comment by ma-bo** [comment]
I posted more explicit workaround directions on the Linux mint forums: https://forums.linuxmint.com/viewtopic.php?p=2378400

**Comment by ma-bo** [comment]
It looks like this problem is specific to Rufus image creation tool.

**Comment by pbatard** [comment]
Rufus dev here.

Just going to point out that the core of the issue is that, as opposed to Debian, the LMDE Mint derivative has not been designed to support [File System Transposition], which, for modern installation images, should really be supported on an equal footing with DD imaging (since it allows people wanting to install Linux to be able to create UEFI installation media on any OS, using the native OS utilities and __without the need to install any third party utility like Rufus, Etcher and whatnot__).

In short, the problem is that the LMDE6 ISO uses a Rock Ridge symlink that has `/live/` point to the `/casper/` directory, that contains initrd and the large squashfs image, and you simply should not rely on symlinks if you want to support File System Transposition, since this is not a feature that can ever be supported on file systems like FAT32.

So, ideally, the `/live/` and `/casper/` should be merged into a single non symlinked directory (why does Mint need two separate directories with the same data?) because the alternative, for utilities __and people__ who want to work with File System Transposition, is to duplicate the content of the directory, which is less than ideal when said directory contains a > 2GB file...

It should also be noted that Rufus does produce the following warning in its log when loading the LMDE6 ISO:
```
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
```

**Comment by pbatard** [comment]
Just a note that the 4.3 BETA of Rufus, which can be downloaded [here](https://rufus.ie/downloads/) is now enforcing the use of NTFS with LMDE in order to symlinks, which **may** help with the issue referenced above. I have not tested the installation however, and chances are that the use of NTFS may create issues elsewhere.

It should also be noted that this is just a __workaround__ as the root of the issue, which I believe should be addressed by the Mint maintainers, is that, unlike Debian, Mint LMDE is lacking support for File System Transposition, and you shouldn't expect Mint users, who don't want to use third party utilities to create a (UEFI) bootable media to resort to having to create symlinks manually...

**Comment by linuxnotes** [comment]
I have the same problem when using unetbootin 677 for flash creation. Usb flash should be formatted to fat32, it can no have synlinks.
Install with using workaround. Thanks.
