### ISSUE TITLE
LMDE 4 beta: No encryption of entire system in manual partitioning mode

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/live-installer#99]
Dear Clem, LMDE 4 beta runs very well. No problems so far. I love it. Excellent job and thank you very much for your great work.

Nice to see, you added LVM and encryption of the entire system to the automated installation. It is, however, missing in the manual partitioning mode. Many users like me have other systems on the hard drive, so wiping the complete disk for an automated installation is not an option. The ability to encrypt the entire system including root directory (not only /home) is essential nowadays. Would it be possible to add this valuable feature to the manual partitioning mode also? LMDE 3 offered Calamares, which was capable of doing so (without LVM, though). Now in LMDE 4 without Calamares the situation is worse than before.

Best regards

**Comment by harlekin777** [comment]
Another possible solution would be to include Calamares again.

**Comment by monsta** [comment]
Calamares goes a bit far with it... even with only one encrypted partition (the actual installation), the passphrase is asked even before GRUB menu appears. I guess that's because there's no unencrypted `/boot` partition. So it means you have to unlock LMDE installation even if you're going to boot some other one. I don't know, maybe it was some error on my side.

**Comment by harlekin777** [comment]
Thank you. You are right about Calamares. Clem already decided to close the same issue as this one, which I posted under lmde-4-cinnamon-beta/issues (outside of scope). So you may close this one, too.

**Comment by monsta** [comment]
I think it can be considered for LMDE 5 (it's all up to Clem of course).
